spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.153.132:3306/dplus_metadata?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: dplus
    password: 123456
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8086
  compression:
    enabled: true
    min-response-size: 2048
    max-http-header-size: 10000000
    mime-types: application/json,application/xml,text/html,text/xml,text/plain